name: Build & Push Frontend (Flutter Web) Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Build Flutter Web
        working-directory: ./frontend
        run: flutter build web

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image (usando Dockerfile en frontend/)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/publictransitagency-frontend:latest -f frontend/Dockerfile frontend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/publictransitagency-frontend:latest
