name: Build & Deploy Flutter Web Frontend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Ajusta si usas otra versión

      - name: Limpiar build anterior
        working-directory: ./src/frontend
        run: flutter clean

      - name: Build Flutter Web (con BACKEND_URL de Railway)
        working-directory: ./src/frontend
        run: flutter build web --dart-define=BACKEND_URL=https://publictransitagency-production.up.railway.app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/publictransitagency-frontend:latest -f ./src/frontend/Dockerfile ./src/frontend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/publictransitagency-frontend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: transitagencywebapp # Cambia por el nombre de tu Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/publictransitagency-frontend:latest
