name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      DB: ${{ secrets.DB }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ALGORITHM: ${{ secrets.ALGORITHM }}

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run the Docker container with secrets
      run: |
        docker run -d -p 8000:8000 \
          -e SECRET_KEY=$SECRET_KEY \
          -e HOST=$HOST \
          -e PORT=$PORT \
          -e DB=$DB \
          -e USER=$USER \
          -e PASSWORD=$PASSWORD \
          -e ALGORITHM=$ALGORITHM \
          my-image-name:$(date +%s)