name: Escaneo de Seguridad OWASP ZAP (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Levanta el contenedor FastAPI
        run: |
          docker pull gitzerohub/publictransitagency:latest
          docker run -d --name app -p 8000:8000 gitzerohub/publictransitagency:latest
          sleep 15  # Ajusta si tu app tarda más en levantar

      - name: Verifica que FastAPI responde
        run: curl http://localhost:8000/docs

      - name: Escanear API con OWASP ZAP
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://host.docker.internal:8000/docs'
          artifact_name: 'zap-report'

      - name: Subir reporte de ZAP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
