name: Escaneo de Seguridad OWASP ZAP (Docker manual)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Levanta el contenedor FastAPI
        run: |
          docker pull gitzerohub/publictransitagency:latest
          docker run -d --name app -p 8000:8000 \
            -e HOST=${{ secrets.HOST }} \
            -e PORT=${{ secrets.PORT }} \
            -e DB=${{ secrets.DB }} \
            -e USER=${{ secrets.USER }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
            gitzerohub/publictransitagency:latest
          sleep 25

      - name: Verifica que FastAPI responde
        run: curl --retry 10 --retry-delay 5 http://127.0.0.1:8000/docs

      - name: Escanear API con OWASP ZAP (docker run manual)
        run: |
          docker run --name zapscan --network=host \
            -v ${{ github.workspace }}:/zap/wrk \
            -w /zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://127.0.0.1:8000/docs \
              --output-dir . \
              -J report_json.json \
              -w report_md.md \
              -r report_html.html

      - name: Mostrar reporte ZAP en logs (markdown)
        run: |
          echo "========== INICIO REPORTE ZAP (MD) =========="
          cat report_md.md || echo "No se generó el archivo report_md.md"
          echo "========== FIN REPORTE ZAP (MD) =========="

      - name: Mostrar reporte ZAP en logs (html)
        run: |
          echo "========== INICIO REPORTE ZAP (HTML) =========="
          cat report_html.html || echo "No se generó el archivo report_html.html"
          echo "========== FIN REPORTE ZAP (HTML) =========="
