name: Escaneo Completo API OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Levanta el contenedor FastAPI
        run: |
          docker pull gitzerohub/publictransitagency:latest
          docker run -d --name app -p 8000:8000 \
            -e HOST=${{ secrets.HOST }} \
            -e PORT=${{ secrets.PORT }} \
            -e DB=${{ secrets.DB }} \
            -e USER=${{ secrets.USER }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
            gitzerohub/publictransitagency:latest
          sleep 25

      - name: Verifica que FastAPI responde
        run: curl --retry 10 --retry-delay 5 http://127.0.0.1:8000/openapi.json

      - name: Descarga el esquema OpenAPI
        run: curl -o openapi.json http://127.0.0.1:8000/openapi.json

      - name: Da permisos de escritura al workspace
        run: sudo chmod -R 777 ${{ github.workspace }}

      - name: Escanear toda la API con OWASP ZAP usando OpenAPI
        run: |
          docker run --name zapscan --network=host \
            -v ${{ github.workspace }}:/zap/wrk \
            -w /zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py \
              -f openapi \
              -t http://127.0.0.1:8000/openapi.json \
              -J report_json.json \
              -w report_md.md \
              -r report_html.html
          docker logs zapscan || echo "No logs disponibles"
          docker rm -f zapscan || true

      - name: Sube los reportes como artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-reportes
          path: |
            report_html.html
            report_md.md
            report_json.json
