name: Escaneo de Seguridad OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Exporta PYTHONPATH y levanta FastAPI
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          uvicorn backend.app.api.main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Escanear API con OWASP ZAP
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8000/docs'
          artifact_name: 'zap-report'

      - name: Subir reporte de ZAP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
