name: Escaneo de Seguridad OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias y levantar FastAPI
        run: |
          pip install -r requirements.txt
          # Cambia 'app.main:app' por el módulo y objeto de tu app FastAPI
          uvicorn src.backend.app.api.main:app --host 0.0.0.0 --port 8000 &
          sleep 8  # Espera a que el servidor arranque

      - name: Escanear API con OWASP ZAP (usando Swagger/OpenAPI)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://127.0.0.1:8000/docs'
          report: 'zap_report.html'

      - name: Subir reporte de ZAP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
