name: Escaneo de Seguridad OWASP ZAP (Docker manual)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Levanta el contenedor FastAPI
        run: |
          docker pull gitzerohub/publictransitagency:latest
          docker run -d --name app -p 8000:8000 \
            -e HOST=${{ secrets.HOST }} \
            -e PORT=${{ secrets.PORT }} \
            -e DB=${{ secrets.DB }} \
            -e USER=${{ secrets.USER }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
            gitzerohub/publictransitagency:latest
          sleep 20

      - name: Da permisos de escritura a la carpeta de trabajo
        run: chmod -R 777 ${{ github.workspace }}

      - name: Verifica que FastAPI responde
        run: curl http://localhost:8000/docs

      - name: Debug path
        run: |
          echo "Workspace: ${{ github.workspace }}"
          ls -la ${{ github.workspace }}

      - name: Escanear API con OWASP ZAP (docker run manual)
        run: |
          docker run --rm \
            --network=host \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://localhost:8000/docs \
              -J /tmp/report_json.json \
              -w /tmp/report_md.md \
              -r /tmp/report_html.html
          docker cp $(docker ps -alq):/tmp/report_html.html ./report_html.html || echo "No se pudo copiar report_html.html"
          docker cp $(docker ps -alq):/tmp/report_md.md ./report_md.md || echo "No se pudo copiar report_md.md"

      - name: Mostrar reporte ZAP en logs (markdown)
        run: |
          echo "========== INICIO REPORTE ZAP (MD) =========="
          cat report_md.md || echo "No se generó el archivo report_md.md"
          echo "========== FIN REPORTE ZAP (MD) =========="

      - name: Mostrar reporte ZAP en logs (html)
        run: |
          echo "========== INICIO REPORTE ZAP (HTML) =========="
          cat report_html.html || echo "No se generó el archivo report_html.html"
          echo "========== FIN REPORTE ZAP (HTML) =========="
